<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display all products
     */
    public function index()
    {
        $products = Product::with('subCategory')
            ->latest()
            ->get();

        return response()->json([
            'success' => true,
            'data'    => $products
        ], 200);
    }

    /**
     * Store new product with automatic folder creation
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'sub_categories_id' => 'required|exists:sub_categories,id',
            'name'              => 'required|string|max:255',
            'description'       => 'nullable|string',
            'summary'           => 'nullable|string',
            'base_price'        => 'required|numeric',
            'img'               => 'required|image|mimes:webp,jpg,jpeg,png|max:2048',
            'is_active'         => 'boolean'
        ]);

        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        try {
            return DB::transaction(function () use ($request) {

                // 1️⃣ Create product first (UUID generated by model)
                $product = Product::create([
                    'sub_categories_id' => $request->sub_categories_id,
                    'name'              => $request->name,
                    'description'       => $request->description,
                    'summary'           => $request->summary,
                    'base_price'        => $request->base_price,
                    'is_active'         => $request->is_active ?? true,
                    'img'               => null,
                ]);

                // 2️⃣ Create folder path
                $folderPath = "private/{$product->id}/cover";
                $fileName   = "cover.webp";

                // 3️⃣ Store image (auto create folder)
                $path = $request->file('img')
                    ->storeAs($folderPath, $fileName, 'local');

                // 4️⃣ Update image path in database
                $product->update([
                    'img' => $path
                ]);

                return response()->json([
                    'success' => true,
                    'message' => 'Product created successfully',
                    'data'    => $product
                ], 201);
            });

        } catch (\Exception $e) {

            return response()->json([
                'message' => 'Failed to create product',
                'error'   => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Show single product
     */
    public function show($id)
    {
        $product = Product::with('subCategory')->find($id);

        if (!$product) {
            return response()->json([
                'message' => 'Product not found'
            ], 404);
        }

        return response()->json([
            'success' => true,
            'data'    => $product
        ], 200);
    }

    /**
     * Update product and optionally replace image
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        if (!$product) {
            return response()->json([
                'message' => 'Product not found'
            ], 404);
        }

        $validator = Validator::make($request->all(), [
            'sub_categories_id' => 'sometimes|exists:sub_categories,id',
            'name'              => 'sometimes|string|max:255',
            'description'       => 'nullable|string',
            'summary'           => 'nullable|string',
            'base_price'        => 'sometimes|numeric',
            'img'               => 'sometimes|image|mimes:webp,jpg,jpeg,png|max:2048',
            'is_active'         => 'boolean'
        ]);

        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }

        try {
            DB::beginTransaction();

            // 1️⃣ Update normal fields
            $product->update($request->except('img'));

            // 2️⃣ If new image uploaded → replace
            if ($request->hasFile('img')) {

                $folderPath = "private/{$product->id}/cover";
                $fileName   = "cover.webp";

                // Delete old file if exists
                if (Storage::disk('local')->exists($folderPath . '/' . $fileName)) {
                    Storage::disk('local')->delete($folderPath . '/' . $fileName);
                }

                $path = $request->file('img')
                    ->storeAs($folderPath, $fileName, 'local');

                $product->update([
                    'img' => $path
                ]);
            }

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => 'Product updated successfully',
                'data'    => $product
            ], 200);

        } catch (\Exception $e) {

            DB::rollBack();

            return response()->json([
                'message' => 'Failed to update product',
                'error'   => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Delete product and entire folder
     */
    public function destroy($id)
    {
        $product = Product::find($id);

        if (!$product) {
            return response()->json([
                'message' => 'Product not found'
            ], 404);
        }

        try {
            DB::beginTransaction();

            // Delete folder
            $directory = "private/{$product->id}";

            if (Storage::disk('local')->exists($directory)) {
                Storage::disk('local')->deleteDirectory($directory);
            }

            // Delete database record
            $product->delete();

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => 'Product deleted successfully'
            ], 200);

        } catch (\Exception $e) {

            DB::rollBack();

            return response()->json([
                'message' => 'Failed to delete product',
                'error'   => $e->getMessage()
            ], 500);
        }
    }
}
